"""add rule quality score fields

Revision ID: 03d646bbf837
Revises: 317eeec5fd27
Create Date: 2026-08-21 12:00:51.780399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d646bbf837'
down_revision = '317eeec5fd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quality_score_breakdown', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('quality_score_computed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rule_quality_score'), ['quality_score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_quality_score'))
        batch_op.drop_column('quality_score_computed_at')
        batch_op.drop_column('quality_score_breakdown')
        batch_op.drop_column('quality_score')

    # ### end Alembic commands ###
