"""empty message
Revision ID: 0419cbf0f1fa
Revises: e59277710971
Create Date: 2026-02-03 09:54:23.720732
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '0419cbf0f1fa'
down_revision = 'e59277710971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'bundle_tag_association' not in existing_tables:
        op.create_table('bundle_tag_association',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('uuid', sa.String(length=36), nullable=False),
            sa.Column('bundle_id', sa.Integer(), nullable=False),
            sa.Column('tag_id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('added_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['bundle_id'], ['bundle.id'], ),
            sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('bundle_tag_association', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_bundle_tag_association_uuid'), ['uuid'], unique=True)

    comment_bundle_columns = [col['name'] for col in inspector.get_columns('comment_bundle')]
    if 'reaction' in comment_bundle_columns:
        with op.batch_alter_table('comment_bundle', schema=None) as batch_op:
            batch_op.drop_column('reaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    comment_bundle_columns = [col['name'] for col in inspector.get_columns('comment_bundle')]
    if 'reaction' not in comment_bundle_columns:
        with op.batch_alter_table('comment_bundle', schema=None) as batch_op:
            batch_op.add_column(sa.Column('reaction', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    if 'bundle_tag_association' in existing_tables:
        with op.batch_alter_table('bundle_tag_association', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_bundle_tag_association_uuid'))
        op.drop_table('bundle_tag_association')
    # ### end Alembic commands ###