"""empty message
Revision ID: 05f3d60aff14
Revises: 6b7054a1114d
Create Date: 2025-11-21 09:44:09.048944
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '05f3d60aff14'
down_revision = '6b7054a1114d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    new_rule_columns = [col['name'] for col in inspector.get_columns('new_rule')]
    if 'format' not in new_rule_columns:
        with op.batch_alter_table('new_rule', schema=None) as batch_op:
            batch_op.add_column(sa.Column('format', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    new_rule_columns = [col['name'] for col in inspector.get_columns('new_rule')]
    if 'format' in new_rule_columns:
        with op.batch_alter_table('new_rule', schema=None) as batch_op:
            batch_op.drop_column('format')
    # ### end Alembic commands ###