"""make rule_edit_contribution proposal_id nullable

Revision ID: 08bd356864c4
Revises: 8939171fe124
Create Date: 2026-07-27 13:48:31.214373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bd356864c4'
down_revision = '8939171fe124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_edit_contribution', schema=None) as batch_op:
        batch_op.alter_column('proposal_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_edit_contribution', schema=None) as batch_op:
        batch_op.alter_column('proposal_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
