"""add AIGeneration table

Revision ID: 0a4481c5ae95
Revises: 80d0ba0db20c
Create Date: 2026-08-26 09:25:16.770047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4481c5ae95'
down_revision = '80d0ba0db20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('agent_key', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_generation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_generation_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_generation_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_generation_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_generation_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_generation_uuid'))
        batch_op.drop_index(batch_op.f('ix_ai_generation_rule_id'))
        batch_op.drop_index(batch_op.f('ix_ai_generation_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_generation_agent_key'))

    op.drop_table('ai_generation')
    # ### end Alembic commands ###
