"""add workflow run notification preference

Revision ID: 1214efa032bb
Revises: d2e69587cb46
Create Date: 2026-08-24 10:30:11.694989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1214efa032bb'
down_revision = 'd2e69587cb46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        # server_default backfills existing rows (opt-in by default, matching
        # every other pref_* column); dropped right after so the Python-level
        # model default remains the sole source of truth going forward.
        batch_op.add_column(sa.Column('pref_workflow_runs', sa.Boolean(), nullable=False, server_default=sa.true()))
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.alter_column('pref_workflow_runs', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_column('pref_workflow_runs')

    # ### end Alembic commands ###
