"""empty message

Revision ID: 2b4f18e9669f
Revises: fb94fb8bf99e
Create Date: 2025-10-29 15:25:38.057746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4f18e9669f'
down_revision = 'fb94fb8bf99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importer_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('bad_rules', sa.Integer(), nullable=True),
    sa.Column('imported', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('query_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('count_per_format', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('importer_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_importer_result_bad_rules'), ['bad_rules'], unique=False)
        batch_op.create_index(batch_op.f('ix_importer_result_imported'), ['imported'], unique=False)
        batch_op.create_index(batch_op.f('ix_importer_result_query_date'), ['query_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_importer_result_skipped'), ['skipped'], unique=False)
        batch_op.create_index(batch_op.f('ix_importer_result_total'), ['total'], unique=False)
        batch_op.create_index(batch_op.f('ix_importer_result_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_importer_result_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('importer_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_importer_result_uuid'))
        batch_op.drop_index(batch_op.f('ix_importer_result_user_id'))
        batch_op.drop_index(batch_op.f('ix_importer_result_total'))
        batch_op.drop_index(batch_op.f('ix_importer_result_skipped'))
        batch_op.drop_index(batch_op.f('ix_importer_result_query_date'))
        batch_op.drop_index(batch_op.f('ix_importer_result_imported'))
        batch_op.drop_index(batch_op.f('ix_importer_result_bad_rules'))

    op.drop_table('importer_result')
    # ### end Alembic commands ###
