"""add admin task scheduler tables

Revision ID: 34eba46b209a
Revises: 03d646bbf837
Create Date: 2026-08-24 07:22:37.164778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34eba46b209a'
down_revision = '03d646bbf837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_task_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('target_payload', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trigger_mode', sa.String(length=20), nullable=False),
    sa.Column('run_once_at', sa.DateTime(), nullable=True),
    sa.Column('days_of_week', sa.String(length=20), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('cron_expr', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('depends_on_schedule_id', sa.Integer(), nullable=True),
    sa.Column('depends_on_condition', sa.String(length=20), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_schedule_id'], ['admin_task_schedule.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['editor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_task_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_task_schedule_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_task_schedule_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_task_schedule_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_task_schedule_uuid'), ['uuid'], unique=True)

    op.create_table('admin_task_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('job_uuid', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['admin_task_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_task_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_task_run_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_task_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_task_run_uuid'))

    op.drop_table('admin_task_run')
    with op.batch_alter_table('admin_task_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_task_schedule_uuid'))
        batch_op.drop_index(batch_op.f('ix_admin_task_schedule_task_type'))
        batch_op.drop_index(batch_op.f('ix_admin_task_schedule_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_admin_task_schedule_is_active'))

    op.drop_table('admin_task_schedule')
    # ### end Alembic commands ###
