"""add ai_summary fields to rule

Revision ID: 396146dcaa7c
Revises: c04523593dd6
Create Date: 2026-08-10 09:55:03.698753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396146dcaa7c'
down_revision = 'c04523593dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_summary_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ai_summary_model', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_column('ai_summary_model')
        batch_op.drop_column('ai_summary_generated_at')
        batch_op.drop_column('ai_summary')

    # ### end Alembic commands ###
