"""empty message

Revision ID: 4600d2b14425
Revises: b1d042e518e4
Create Date: 2026-01-19 08:35:49.319621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4600d2b14425'
down_revision = 'b1d042e518e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invalid_rule_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invalid_rule_model', schema=None) as batch_op:
        batch_op.drop_column('github_path')

    # ### end Alembic commands ###
