"""empty message

Revision ID: 49bb142fb116
Revises: 05f3d60aff14
Create Date: 2025-12-15 10:43:45.867156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bb142fb116'
down_revision = '05f3d60aff14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('suggestions_submitted', sa.Integer(), nullable=True),
    sa.Column('suggestions_accepted', sa.Integer(), nullable=True),
    sa.Column('suggestions_rejected', sa.Integer(), nullable=True),
    sa.Column('rules_owned', sa.Integer(), nullable=True),
    sa.Column('rules_popular_score', sa.Integer(), nullable=True),
    sa.Column('rules_liked', sa.Integer(), nullable=True),
    sa.Column('rules_disliked', sa.Integer(), nullable=True),
    sa.Column('last_contribution_date', sa.DateTime(), nullable=True),
    sa.Column('consecutive_days_active', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gamification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gamification_rules_liked'), ['rules_liked'], unique=False)
        batch_op.create_index(batch_op.f('ix_gamification_suggestions_accepted'), ['suggestions_accepted'], unique=False)
        batch_op.create_index(batch_op.f('ix_gamification_total_points'), ['total_points'], unique=False)
        batch_op.create_index(batch_op.f('ix_gamification_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gamification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gamification_uuid'))
        batch_op.drop_index(batch_op.f('ix_gamification_total_points'))
        batch_op.drop_index(batch_op.f('ix_gamification_suggestions_accepted'))
        batch_op.drop_index(batch_op.f('ix_gamification_rules_liked'))

    op.drop_table('gamification')
    # ### end Alembic commands ###
