"""add github_proposal table

Revision ID: 59a6381dbc50
Revises: c3d255d33306
Create Date: 2026-07-29 13:42:40.225999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a6381dbc50'
down_revision = 'c3d255d33306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_proposal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=512), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('ownership_mode', sa.String(length=16), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('job_uuid', sa.String(length=36), nullable=True),
    sa.Column('importer_result_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_proposal_job_uuid'), ['job_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_proposal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_proposal_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_proposal_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_proposal_uuid'))
        batch_op.drop_index(batch_op.f('ix_github_proposal_user_id'))
        batch_op.drop_index(batch_op.f('ix_github_proposal_status'))
        batch_op.drop_index(batch_op.f('ix_github_proposal_job_uuid'))

    op.drop_table('github_proposal')
    # ### end Alembic commands ###
