"""add is_generic_source to github proposal and sync schedule repo

Revision ID: 653504fe1a0c
Revises: a9d81d8324b2
Create Date: 2026-09-07 14:20:23.186714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653504fe1a0c'
down_revision = 'a9d81d8324b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not autogenerated) — without it, adding
    # a NOT NULL column fails outright on any table that already has rows.
    with op.batch_alter_table('github_proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_generic_source', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('github_sync_schedule_repo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_generic_source', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_sync_schedule_repo', schema=None) as batch_op:
        batch_op.drop_column('is_generic_source')

    with op.batch_alter_table('github_proposal', schema=None) as batch_op:
        batch_op.drop_column('is_generic_source')

    # ### end Alembic commands ###
