"""add misp_server table

Revision ID: 665dddd355d8
Revises: d898512a937d
Create Date: 2026-08-05 10:44:02.748364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665dddd355d8'
down_revision = 'd898512a937d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('misp_server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_push_at', sa.DateTime(), nullable=True),
    sa.Column('pushes_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('misp_server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_misp_server_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('misp_server', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_misp_server_uuid'))

    op.drop_table('misp_server')
    # ### end Alembic commands ###
