"""replace rule ai_summary columns with rule_ai_analysis history table

Revision ID: 6843a94ff8db
Revises: 396146dcaa7c
Create Date: 2026-08-10 10:51:21.790293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6843a94ff8db'
down_revision = '396146dcaa7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_model_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('rule_ai_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_ai_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_ai_analysis_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_ai_analysis_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_ai_analysis_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        # server_default required: instance_config already has a row (it's a
        # single-row table, created on first boot), so a NOT NULL column
        # can't be added without a value to backfill it with.
        batch_op.add_column(sa.Column('ai_rule_analysis_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_column('ai_summary')
        batch_op.drop_column('ai_summary_model')
        batch_op.drop_column('ai_summary_generated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_summary_generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_summary_model', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.drop_column('ai_rule_analysis_enabled')

    with op.batch_alter_table('rule_ai_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_ai_analysis_uuid'))
        batch_op.drop_index(batch_op.f('ix_rule_ai_analysis_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_ai_analysis_created_at'))

    op.drop_table('rule_ai_analysis')
    op.drop_table('ai_analysis_model_config')
    # ### end Alembic commands ###
