"""add chatbot_enabled to instance config

Revision ID: 6aa13edf7d3c
Revises: dabdea4793f5
Create Date: 2026-07-23 09:48:46.349739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa13edf7d3c'
down_revision = 'dabdea4793f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chatbot_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.drop_column('chatbot_enabled')

    # ### end Alembic commands ###
