"""empty message

Revision ID: 6b7054a1114d
Revises: 2b4f18e9669f
Create Date: 2025-11-07 10:39:29.477856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7054a1114d'
down_revision = '2b4f18e9669f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('repo_sources', sa.Text(), nullable=True),
    sa.Column('not_found', sa.Integer(), nullable=True),
    sa.Column('found', sa.Integer(), nullable=True),
    sa.Column('updated', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('thread_count', sa.Integer(), nullable=True),
    sa.Column('query_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('update_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_update_result_query_date'), ['query_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_update_result_total'), ['total'], unique=False)
        batch_op.create_index(batch_op.f('ix_update_result_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_update_result_uuid'), ['uuid'], unique=True)

    op.create_table('new_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('update_result_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name_rule', sa.String(), nullable=False),
    sa.Column('rule_content', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rule_syntax_valid', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('accept', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['update_result_id'], ['update_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('new_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_new_rule_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_new_rule_uuid'), ['uuid'], unique=True)

    op.create_table('rule_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('update_result_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('name_rule', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('found', sa.Boolean(), nullable=True),
    sa.Column('update_available', sa.Boolean(), nullable=True),
    sa.Column('rule_syntax_valid', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('history_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['update_result_id'], ['update_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_status_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_status_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_status_uuid'))
        batch_op.drop_index(batch_op.f('ix_rule_status_date'))

    op.drop_table('rule_status')
    with op.batch_alter_table('new_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_new_rule_uuid'))
        batch_op.drop_index(batch_op.f('ix_new_rule_date'))

    op.drop_table('new_rule')
    with op.batch_alter_table('update_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_update_result_uuid'))
        batch_op.drop_index(batch_op.f('ix_update_result_user_id'))
        batch_op.drop_index(batch_op.f('ix_update_result_total'))
        batch_op.drop_index(batch_op.f('ix_update_result_query_date'))

    op.drop_table('update_result')
    # ### end Alembic commands ###
