"""empty message

Revision ID: 70eba8589ac8
Revises: 8f37283a6cfc
Create Date: 2026-02-12 10:31:30.678657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70eba8589ac8'
down_revision = '8f37283a6cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_rules_processed', sa.Integer(), nullable=True),
    sa.Column('similar_pairs_found', sa.Integer(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('similar_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_similar_result_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_similar_result_uuid'), ['uuid'], unique=True)

    op.create_table('rule_similarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('similar_rule_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('result_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['result_uuid'], ['similar_result.uuid'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similar_rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'similar_rule_id', name='_rule_pair_uc')
    )
    with op.batch_alter_table('rule_similarity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_similarity_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_similarity_score'), ['score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_similarity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_similarity_score'))
        batch_op.drop_index(batch_op.f('ix_rule_similarity_rule_id'))

    op.drop_table('rule_similarity')
    with op.batch_alter_table('similar_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_similar_result_uuid'))
        batch_op.drop_index(batch_op.f('ix_similar_result_date'))

    op.drop_table('similar_result')
    # ### end Alembic commands ###
