"""add admin workflow container for task scheduler

Revision ID: 719042cdbf51
Revises: 34eba46b209a
Create Date: 2026-08-24 07:50:48.921771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719042cdbf51'
down_revision = '34eba46b209a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_workflow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_workflow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_workflow_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_workflow_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('admin_task_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_admin_task_schedule_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_foreign_key(None, 'admin_workflow', ['workflow_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_task_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_admin_task_schedule_workflow_id'))
        batch_op.drop_column('workflow_id')

    with op.batch_alter_table('admin_workflow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_workflow_uuid'))
        batch_op.drop_index(batch_op.f('ix_admin_workflow_is_active'))

    op.drop_table('admin_workflow')
    # ### end Alembic commands ###
