"""add chatbot conversation history tables

Revision ID: 7214afa68c9f
Revises: 627f274b2341
Create Date: 2026-07-21 11:53:44.803500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7214afa68c9f'
down_revision = '627f274b2341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_conversation_last_message_at'), ['last_message_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_conversation_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_conversation_uuid'), ['uuid'], unique=True)

    op.create_table('chatbot_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatbot_conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatbot_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_message_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_message_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_message_created_at'))
        batch_op.drop_index(batch_op.f('ix_chatbot_message_conversation_id'))

    op.drop_table('chatbot_message')
    with op.batch_alter_table('chatbot_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_conversation_uuid'))
        batch_op.drop_index(batch_op.f('ix_chatbot_conversation_user_id'))
        batch_op.drop_index(batch_op.f('ix_chatbot_conversation_last_message_at'))

    op.drop_table('chatbot_conversation')
    # ### end Alembic commands ###
