"""empty message

Revision ID: 7532fa2df24d
Revises: 8d4f92a7fec1
Create Date: 2026-01-14 08:13:47.103475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7532fa2df24d'
down_revision = '8d4f92a7fec1'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'auto_update_schedule_rule_association' in existing_tables:
        op.drop_table('auto_update_schedule_rule_association')
    if 'auto_update_schedule' in existing_tables:
        op.drop_table('auto_update_schedule')

    with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_rule_update_history_rule_id_rule', 'rule', ['rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_update_schedule',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('auto_update_schedule_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minute', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('days', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='auto_update_schedule_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='auto_update_schedule_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auto_update_schedule_rule_association',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], name=op.f('auto_update_schedule_rule_association_rule_id_fkey')),
    sa.ForeignKeyConstraint(['schedule_id'], ['auto_update_schedule.id'], name=op.f('auto_update_schedule_rule_association_schedule_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('auto_update_schedule_rule_association_pkey'))
    )
    # with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    # ### end Alembic commands ###
