"""Add log_action_definition table

Revision ID: 7b3d3c01f9ec
Revises: 86f2cd9a3396
Create Date: 2026-07-03 13:59:56.102212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3d3c01f9ec'
down_revision = '86f2cd9a3396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_action_definition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_key', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_action_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_action_definition_action_key'), ['action_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_action_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_action_definition_action_key'))

    op.drop_table('log_action_definition')
    # ### end Alembic commands ###
