"""empty message
Revision ID: 7c29ff29bff2
Revises: 7e96e200dc91
Create Date: 2026-01-20 14:38:29.824569
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '7c29ff29bff2'
down_revision = '7e96e200dc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('bundle_node')]
    with op.batch_alter_table('bundle_node', schema=None) as batch_op:
        if 'bundle_node_rule_id_fkey' in existing_fks:
            batch_op.drop_constraint(batch_op.f('bundle_node_rule_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rule', ['rule_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('bundle_node')]
    with op.batch_alter_table('bundle_node', schema=None) as batch_op:
        if None in existing_fks or any(fk for fk in inspector.get_foreign_keys('bundle_node') if fk.get('referred_table') == 'rule' and fk.get('name') is None):
            batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bundle_node_rule_id_fkey'), 'rule', ['rule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###