"""empty message

Revision ID: 7c29ff29bff2
Revises: 7e96e200dc91
Create Date: 2026-01-20 14:38:29.824569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c29ff29bff2'
down_revision = '7e96e200dc91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle_node', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bundle_node_rule_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rule', ['rule_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle_node', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bundle_node_rule_id_fkey'), 'rule', ['rule_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
