"""empty message
Revision ID: 7e96e200dc91
Revises: a8db63c0719b
Create Date: 2026-01-20 10:52:28.163402
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '7e96e200dc91'
down_revision = 'a8db63c0719b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'bundle_node' not in existing_tables:
        op.create_table('bundle_node',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('bundle_id', sa.Integer(), nullable=False),
            sa.Column('parent_id', sa.Integer(), nullable=True),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('node_type', sa.String(length=50), nullable=False),
            sa.Column('custom_content', sa.Text(), nullable=True),
            sa.Column('rule_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['bundle_id'], ['bundle.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['parent_id'], ['bundle_node.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id')
        )

    bundle_columns = {col['name']: col for col in inspector.get_columns('bundle')}
    with op.batch_alter_table('bundle', schema=None) as batch_op:
        if 'view_count' in bundle_columns and not bundle_columns['view_count']['nullable']:
            batch_op.alter_column('view_count',
                existing_type=sa.INTEGER(),
                nullable=True,
                existing_server_default=sa.text('0'))
        if 'download_count' in bundle_columns and not bundle_columns['download_count']['nullable']:
            batch_op.alter_column('download_count',
                existing_type=sa.INTEGER(),
                nullable=True,
                existing_server_default=sa.text('0'))
        if 'is_verified' in bundle_columns and not bundle_columns['is_verified']['nullable']:
            batch_op.alter_column('is_verified',
                existing_type=sa.BOOLEAN(),
                nullable=True,
                existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    bundle_columns = {col['name']: col for col in inspector.get_columns('bundle')}
    with op.batch_alter_table('bundle', schema=None) as batch_op:
        if 'is_verified' in bundle_columns and bundle_columns['is_verified']['nullable']:
            batch_op.alter_column('is_verified',
                existing_type=sa.BOOLEAN(),
                nullable=False,
                existing_server_default=sa.text('false'))
        if 'download_count' in bundle_columns and bundle_columns['download_count']['nullable']:
            batch_op.alter_column('download_count',
                existing_type=sa.INTEGER(),
                nullable=False,
                existing_server_default=sa.text('0'))
        if 'view_count' in bundle_columns and bundle_columns['view_count']['nullable']:
            batch_op.alter_column('view_count',
                existing_type=sa.INTEGER(),
                nullable=False,
                existing_server_default=sa.text('0'))

    if 'bundle_node' in existing_tables:
        op.drop_table('bundle_node')
    # ### end Alembic commands ###