"""add AI foundation tables (ai_agent_config, ai_model_config, ai_execution_log)

Revision ID: 80d0ba0db20c
Revises: 1214efa032bb
Create Date: 2026-08-26 09:03:33.051258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d0ba0db20c'
down_revision = '1214efa032bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_key', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('default_model', sa.String(length=128), nullable=True),
    sa.Column('max_per_hour', sa.Integer(), nullable=True),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('num_predict', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_agent_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_agent_config_agent_key'), ['agent_key'], unique=True)

    op.create_table('ai_model_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('ai_execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('agent_key', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('input_summary', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('flagged_reason', sa.String(length=200), nullable=True),
    sa.Column('iteration_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_execution_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_execution_log_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_execution_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_execution_log_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_execution_log_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_execution_log_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_execution_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_execution_log_uuid'))
        batch_op.drop_index(batch_op.f('ix_ai_execution_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_execution_log_rule_id'))
        batch_op.drop_index(batch_op.f('ix_ai_execution_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_execution_log_agent_key'))

    op.drop_table('ai_execution_log')
    op.drop_table('ai_model_config')
    with op.batch_alter_table('ai_agent_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_agent_config_agent_key'))

    op.drop_table('ai_agent_config')
    # ### end Alembic commands ###
