"""Add pivotick_background table

Revision ID: 84fa91f73d5a
Revises: 7b3d3c01f9ec
Create Date: 2026-07-03 16:11:32.676610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fa91f73d5a'
down_revision = '7b3d3c01f9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pivotick_background',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pivotick_background', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pivotick_background_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pivotick_background', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pivotick_background_uuid'))

    op.drop_table('pivotick_background')
    # ### end Alembic commands ###
