"""add github_issue_url and github_issue_number to comment_v2

Revision ID: 86f2cd9a3396
Revises: 22560ae69b74
Create Date: 2026-07-03 08:54:47.144230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f2cd9a3396'
down_revision = '22560ae69b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_v2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_issue_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('github_issue_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_v2', schema=None) as batch_op:
        batch_op.drop_column('github_issue_number')
        batch_op.drop_column('github_issue_url')

    # ### end Alembic commands ###
