"""add metadata snapshot fields to rule_update_history

Revision ID: 8939171fe124
Revises: 6aa13edf7d3c
Create Date: 2026-07-27 11:45:14.474192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8939171fe124'
down_revision = '6aa13edf7d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('new_snapshot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('change_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
        batch_op.drop_column('change_type')
        batch_op.drop_column('new_snapshot')
        batch_op.drop_column('old_snapshot')

    # ### end Alembic commands ###
