from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4f92a7fec1'
down_revision = 'e430cce3d08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
        # Ajout de la colonne avec default False
        batch_op.add_column(
            sa.Column(
                'manuel_submit',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false()  
            )
        )

   
    op.execute("UPDATE rule_update_history SET manuel_submit = FALSE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
        batch_op.drop_column('manuel_submit')
    # ### end Alembic commands ###
