"""empty message
Revision ID: 8d4f92a7fec1
Revises: e430cce3d08c
Create Date: ...
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '8d4f92a7fec1'
down_revision = 'e430cce3d08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [col['name'] for col in inspector.get_columns('rule_update_history')]
    if 'manuel_submit' not in columns:
        with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    'manuel_submit',
                    sa.Boolean(),
                    nullable=False,
                    server_default=sa.false()
                )
            )
        op.execute("UPDATE rule_update_history SET manuel_submit = FALSE")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [col['name'] for col in inspector.get_columns('rule_update_history')]
    if 'manuel_submit' in columns:
        with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
            batch_op.drop_column('manuel_submit')
    # ### end Alembic commands ###