"""make ai_generation.rule_id nullable

Revision ID: 8d9880f5f85f
Revises: 0a4481c5ae95
Create Date: 2026-08-26 11:26:22.962341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9880f5f85f'
down_revision = '0a4481c5ae95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generation', schema=None) as batch_op:
        batch_op.alter_column('rule_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generation', schema=None) as batch_op:
        batch_op.alter_column('rule_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
