"""empty message

Revision ID: 8f37283a6cfc
Revises: f1acce46e588
Create Date: 2026-02-10 08:25:42.635283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f37283a6cfc'
down_revision = 'f1acce46e588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_tag_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_tag_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_tag_association_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
        batch_op.alter_column('manuel_submit',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=255), nullable=True))

    tag_table = sa.table('tag', sa.column('source', sa.String))
    op.execute(
        tag_table.update().values(source='Taxonomy')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
        batch_op.alter_column('manuel_submit',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('rule_tag_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_tag_association_uuid'))

    op.drop_table('rule_tag_association')
    # ### end Alembic commands ###
