"""empty message
Revision ID: 8f37283a6cfc
Revises: f1acce46e588
Create Date: 2026-02-10 08:25:42.635283
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '8f37283a6cfc'
down_revision = 'f1acce46e588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'rule_tag_association' not in existing_tables:
        op.create_table('rule_tag_association',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('uuid', sa.String(length=36), nullable=False),
            sa.Column('rule_id', sa.Integer(), nullable=False),
            sa.Column('tag_id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('added_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
            sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('rule_tag_association', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rule_tag_association_uuid'), ['uuid'], unique=True)

    rule_update_history_columns = {col['name']: col for col in inspector.get_columns('rule_update_history')}
    if 'manuel_submit' in rule_update_history_columns and not rule_update_history_columns['manuel_submit']['nullable']:
        with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
            batch_op.alter_column('manuel_submit',
                existing_type=sa.BOOLEAN(),
                nullable=True,
                existing_server_default=sa.text('false'))

    tag_columns = [col['name'] for col in inspector.get_columns('tag')]
    if 'source' not in tag_columns:
        with op.batch_alter_table('tag', schema=None) as batch_op:
            batch_op.add_column(sa.Column('source', sa.String(length=255), nullable=True))
        tag_table = sa.table('tag', sa.column('source', sa.String))
        op.execute(tag_table.update().values(source='Taxonomy'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    tag_columns = [col['name'] for col in inspector.get_columns('tag')]
    if 'source' in tag_columns:
        with op.batch_alter_table('tag', schema=None) as batch_op:
            batch_op.drop_column('source')

    rule_update_history_columns = {col['name']: col for col in inspector.get_columns('rule_update_history')}
    if 'manuel_submit' in rule_update_history_columns and rule_update_history_columns['manuel_submit']['nullable']:
        with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
            batch_op.alter_column('manuel_submit',
                existing_type=sa.BOOLEAN(),
                nullable=False,
                existing_server_default=sa.text('false'))

    if 'rule_tag_association' in existing_tables:
        with op.batch_alter_table('rule_tag_association', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_rule_tag_association_uuid'))
        op.drop_table('rule_tag_association')
    # ### end Alembic commands ###