"""empty message

Revision ID: 98d339abb265
Revises: 4600d2b14425
Create Date: 2026-01-19 08:44:36.737629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d339abb265'
down_revision = '4600d2b14425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_rule', schema=None) as batch_op:
        batch_op.drop_column('github_path')

    # ### end Alembic commands ###
