"""add workflow-level notification settings

Revision ID: a495b3d89373
Revises: 719042cdbf51
Create Date: 2026-08-24 08:16:34.994737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a495b3d89373'
down_revision = '719042cdbf51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted: existing rows need a
    # default so the NOT NULL columns can be added without failing. ###
    with op.batch_alter_table('admin_workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_on_failure', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('notify_on_success', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('notify_emails', sa.JSON(), nullable=True))

    with op.batch_alter_table('admin_workflow', schema=None) as batch_op:
        batch_op.alter_column('notify_on_failure', server_default=None)
        batch_op.alter_column('notify_on_success', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_workflow', schema=None) as batch_op:
        batch_op.drop_column('notify_emails')
        batch_op.drop_column('notify_on_success')
        batch_op.drop_column('notify_on_failure')

    # ### end Alembic commands ###
