"""empty message
Revision ID: b1d042e518e4
Revises: 7532fa2df24d
Create Date: 2026-01-14 09:45:12.255121
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'b1d042e518e4'
down_revision = '7532fa2df24d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [col['name'] for col in inspector.get_columns('rule')]
    if 'github_path' not in columns:
        with op.batch_alter_table('rule', schema=None) as batch_op:
            batch_op.add_column(sa.Column('github_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [col['name'] for col in inspector.get_columns('rule')]
    if 'github_path' in columns:
        with op.batch_alter_table('rule', schema=None) as batch_op:
            batch_op.drop_column('github_path')
    # ### end Alembic commands ###