"""empty message

Revision ID: b3f94ec1b438
Revises: e59277710971
Create Date: 2026-02-03 07:57:14.435689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f94ec1b438'
down_revision = 'e59277710971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_bundle', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('ix_comment_bundle_active'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_bundle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_bundle_active'), ['active'], unique=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
