"""empty message

Revision ID: ba82799e93d3
Revises: 7c29ff29bff2
Create Date: 2026-02-02 09:40:20.632958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba82799e93d3'
down_revision = '7c29ff29bff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_bundle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('reaction', sa.String(length=50), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundle.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment_bundle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment_bundle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_bundle_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_bundle_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_bundle_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_bundle_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_bundle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_bundle_uuid'))
        batch_op.drop_index(batch_op.f('ix_comment_bundle_updated_at'))
        batch_op.drop_index(batch_op.f('ix_comment_bundle_id'))
        batch_op.drop_index(batch_op.f('ix_comment_bundle_created_at'))

    op.drop_table('comment_bundle')
    # ### end Alembic commands ###
