"""add indexes on rule_id FK columns for fast trash purge

Revision ID: bb7f238bf900
Revises: 8d9880f5f85f
Create Date: 2026-08-31 09:05:12.145108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7f238bf900'
down_revision = '8d9880f5f85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle_rule_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bundle_rule_association_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('repport_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repport_rule_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('request_owner_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_owner_rule_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('rule_attack_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_attack_association_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('rule_comment_reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_comment_reaction_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('rule_edit_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_edit_comment_proposal_id'), ['proposal_id'], unique=False)

    with op.batch_alter_table('rule_edit_contribution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_edit_contribution_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('rule_edit_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_edit_proposal_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('rule_favorite_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_favorite_user_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('rule_similarity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_similarity_similar_rule_id'), ['similar_rule_id'], unique=False)

    with op.batch_alter_table('rule_tag_association', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_tag_association_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_update_history_rule_id'), ['rule_id'], unique=False)

    with op.batch_alter_table('rule_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_vote_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_vote_rule_id'))

    with op.batch_alter_table('rule_update_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_update_history_rule_id'))

    with op.batch_alter_table('rule_tag_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_tag_association_rule_id'))

    with op.batch_alter_table('rule_similarity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_similarity_similar_rule_id'))

    with op.batch_alter_table('rule_favorite_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_favorite_user_rule_id'))

    with op.batch_alter_table('rule_edit_proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_edit_proposal_rule_id'))

    with op.batch_alter_table('rule_edit_contribution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_edit_contribution_rule_id'))

    with op.batch_alter_table('rule_edit_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_edit_comment_proposal_id'))

    with op.batch_alter_table('rule_comment_reaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_comment_reaction_rule_id'))

    with op.batch_alter_table('rule_attack_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_attack_association_rule_id'))

    with op.batch_alter_table('request_owner_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_owner_rule_rule_id'))

    with op.batch_alter_table('repport_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repport_rule_rule_id'))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_rule_id'))

    with op.batch_alter_table('bundle_rule_association', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bundle_rule_association_rule_id'))

    # ### end Alembic commands ###
