"""add similar_pairs_skipped to similar_result

Revision ID: c04523593dd6
Revises: bae6d35e98f0
Create Date: 2026-08-10 07:48:45.840148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04523593dd6'
down_revision = 'bae6d35e98f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similar_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('similar_pairs_skipped', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('similar_result', schema=None) as batch_op:
        batch_op.drop_column('similar_pairs_skipped')

    # ### end Alembic commands ###
