"""add velociraptor_server table

Revision ID: c3d255d33306
Revises: 08bd356864c4
Create Date: 2026-07-28 09:20:04.737461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d255d33306'
down_revision = '08bd356864c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('velociraptor_server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_connection_string', sa.String(length=255), nullable=False),
    sa.Column('ca_certificate', sa.Text(), nullable=False),
    sa.Column('client_cert_encrypted', sa.Text(), nullable=False),
    sa.Column('client_key_encrypted', sa.Text(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_push_at', sa.DateTime(), nullable=True),
    sa.Column('artifacts_pushed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('velociraptor_server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_velociraptor_server_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('velociraptor_server', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_velociraptor_server_uuid'))

    op.drop_table('velociraptor_server')
    # ### end Alembic commands ###
