"""empty message
Revision ID: c9c25261bb0b
Revises: 70eba8589ac8
Create Date: 2026-03-16 14:59:06.822937
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'c9c25261bb0b'
down_revision = '70eba8589ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [col['name'] for col in inspector.get_columns('rule_edit_proposal')]
    existing_fks = [fk['name'] for fk in inspector.get_foreign_keys('rule_edit_proposal')]

    with op.batch_alter_table('rule_edit_proposal', schema=None) as batch_op:
        if 'edit_type' not in columns:
            batch_op.add_column(sa.Column('edit_type', sa.String(length=50), nullable=True))
        if 'change_score' not in columns:
            batch_op.add_column(sa.Column('change_score', sa.Float(), nullable=True))
        if 'reviewed_by_id' not in columns:
            batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        if 'reviewed_at' not in columns:
            batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        if 'rejection_reason' not in columns:
            batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.alter_column('old_content',
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            existing_nullable=True)
        if not any(fk for fk in inspector.get_foreign_keys('rule_edit_proposal')
                   if fk.get('referred_table') == 'user' and 'reviewed_by_id' in fk.get('constrained_columns', [])):
            batch_op.create_foreign_key(None, 'user', ['reviewed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [col['name'] for col in inspector.get_columns('rule_edit_proposal')]

    with op.batch_alter_table('rule_edit_proposal', schema=None) as batch_op:
        fk_to_drop = next((fk for fk in inspector.get_foreign_keys('rule_edit_proposal')
                           if fk.get('referred_table') == 'user' and 'reviewed_by_id' in fk.get('constrained_columns', [])), None)
        if fk_to_drop:
            batch_op.drop_constraint(fk_to_drop['name'], type_='foreignkey')
        batch_op.alter_column('old_content',
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True)
        if 'rejection_reason' in columns:
            batch_op.drop_column('rejection_reason')
        if 'reviewed_at' in columns:
            batch_op.drop_column('reviewed_at')
        if 'reviewed_by_id' in columns:
            batch_op.drop_column('reviewed_by_id')
        if 'change_score' in columns:
            batch_op.drop_column('change_score')
        if 'edit_type' in columns:
            batch_op.drop_column('edit_type')
    # ### end Alembic commands ###