"""add error_count to chatbot_conversation

Revision ID: cfc5e433271f
Revises: 7214afa68c9f
Create Date: 2026-07-21 12:02:46.055426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc5e433271f'
down_revision = '7214afa68c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_chatbot_conversation_error_count'), ['error_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatbot_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_conversation_error_count'))
        batch_op.drop_column('error_count')

    # ### end Alembic commands ###
