"""add canvas position to admin task schedule

Revision ID: d2e69587cb46
Revises: f3d2ac0d7966
Create Date: 2026-08-24 09:22:10.463719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e69587cb46'
down_revision = 'f3d2ac0d7966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_task_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('position_y', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_task_schedule', schema=None) as batch_op:
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')

    # ### end Alembic commands ###
