"""Add pivotick_graph_style table

Revision ID: d898512a937d
Revises: 59a6381dbc50
Create Date: 2026-07-30 07:48:50.557691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd898512a937d'
down_revision = '59a6381dbc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pivotick_graph_style',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('graph_type', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pivotick_graph_style', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pivotick_graph_style_graph_type'), ['graph_type'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pivotick_graph_style', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pivotick_graph_style_graph_type'))

    op.drop_table('pivotick_graph_style')
    # ### end Alembic commands ###
