"""empty message
Revision ID: d90028257bb1
Revises: 67d889c747bf
Create Date: 2026-02-04 13:52:13.671027
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'd90028257bb1'
down_revision = '67d889c747bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    bundle_columns = {col['name']: col for col in inspector.get_columns('bundle')}
    if 'vulnerability_identifiers' in bundle_columns and not bundle_columns['vulnerability_identifiers']['nullable']:
        with op.batch_alter_table('bundle', schema=None) as batch_op:
            batch_op.alter_column('vulnerability_identifiers',
                existing_type=sa.TEXT(),
                nullable=True,
                existing_server_default=sa.text("'[]'::text"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    bundle_columns = {col['name']: col for col in inspector.get_columns('bundle')}
    if 'vulnerability_identifiers' in bundle_columns and bundle_columns['vulnerability_identifiers']['nullable']:
        with op.batch_alter_table('bundle', schema=None) as batch_op:
            batch_op.alter_column('vulnerability_identifiers',
                existing_type=sa.TEXT(),
                nullable=False,
                existing_server_default=sa.text("'[]'::text"))
    # ### end Alembic commands ###