"""add content_hash to rule

Revision ID: e18be6e29da8
Revises: 627f274b2341
Create Date: 2026-07-22 07:16:22.145392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18be6e29da8'
down_revision = '627f274b2341'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=32), nullable=True))

    # Backfill existing rows — same normalization as compute_rule_content_hash()
    # in app/core/db_class/db.py (strip space/\n/\r/\t, lowercase, md5).
    op.execute("""
        UPDATE rule
        SET content_hash = md5(
            lower(replace(replace(replace(replace(to_string, ' ', ''), chr(10), ''), chr(13), ''), chr(9), ''))
        )
        WHERE to_string IS NOT NULL
    """)

    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_content_hash'), ['content_hash'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_content_hash'))
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
