"""empty message
Revision ID: e430cce3d08c
Revises: 3fcb1d344dfb
Create Date: 2026-01-07 14:33:36.845183
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'e430cce3d08c'
down_revision = '3fcb1d344dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [col['name'] for col in inspector.get_columns('tag')]
    if 'external_id' not in columns:
        with op.batch_alter_table('tag', schema=None) as batch_op:
            batch_op.add_column(sa.Column('external_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    columns = [col['name'] for col in inspector.get_columns('tag')]
    if 'external_id' in columns:
        with op.batch_alter_table('tag', schema=None) as batch_op:
            batch_op.drop_column('external_id')
    # ### end Alembic commands ###