"""empty message

Revision ID: e59277710971
Revises: ba82799e93d3
Create Date: 2026-02-02 11:32:43.793875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59277710971'
down_revision = 'ba82799e93d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle_reaction_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundle.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comment_bundle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bundle_reaction_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bundle_reaction_comment_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle_reaction_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bundle_reaction_comment_uuid'))

    op.drop_table('bundle_reaction_comment')
    # ### end Alembic commands ###
