"""add mascot_enabled to instance config

Revision ID: e862097a8d21
Revises: bb7f238bf900
Create Date: 2026-09-02 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e862097a8d21'
down_revision = 'bb7f238bf900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mascot_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.drop_column('mascot_enabled')

    # ### end Alembic commands ###
