"""add github sync schedule tables and notification pref

Revision ID: e8d54710ad78
Revises: e18be6e29da8
Create Date: 2026-07-22 13:38:14.269933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d54710ad78'
down_revision = 'e18be6e29da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_sync_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('days_of_week', sa.String(length=20), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('cron_expr', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['editor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_sync_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_sync_schedule_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_sync_schedule_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_github_sync_schedule_uuid'), ['uuid'], unique=True)

    op.create_table('github_sync_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('job_uuid', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['github_sync_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_sync_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_github_sync_run_uuid'), ['uuid'], unique=True)

    op.create_table('github_sync_schedule_repo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('auto_accept_update', sa.Boolean(), nullable=True),
    sa.Column('auto_add_new_rule', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['github_sync_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'repo_url', name='uq_schedule_repo')
    )
    op.create_table('github_sync_run_repo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('update_result_uuid', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('auto_accepted', sa.Integer(), nullable=True),
    sa.Column('auto_rejected', sa.Integer(), nullable=True),
    sa.Column('auto_added', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['github_sync_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pref_sync_run_finished', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_column('pref_sync_run_finished')

    op.drop_table('github_sync_run_repo')
    op.drop_table('github_sync_schedule_repo')
    with op.batch_alter_table('github_sync_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_sync_run_uuid'))

    op.drop_table('github_sync_run')
    with op.batch_alter_table('github_sync_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_github_sync_schedule_uuid'))
        batch_op.drop_index(batch_op.f('ix_github_sync_schedule_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_github_sync_schedule_is_active'))

    op.drop_table('github_sync_schedule')
    # ### end Alembic commands ###
