"""empty message
Revision ID: f1acce46e588
Revises: d90028257bb1
Create Date: 2026-02-04 13:54:31.590367
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect, Text, String

# revision identifiers, used by Alembic.
revision = 'f1acce46e588'
down_revision = 'd90028257bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    rule_columns = {col['name']: col for col in inspector.get_columns('rule')}
    if 'cve_id' in rule_columns and not isinstance(rule_columns['cve_id']['type'], Text):
        with op.batch_alter_table('rule', schema=None) as batch_op:
            batch_op.alter_column('cve_id',
                existing_type=sa.VARCHAR(),
                type_=sa.Text(),
                existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    rule_columns = {col['name']: col for col in inspector.get_columns('rule')}
    if 'cve_id' in rule_columns and isinstance(rule_columns['cve_id']['type'], Text):
        with op.batch_alter_table('rule', schema=None) as batch_op:
            batch_op.alter_column('cve_id',
                existing_type=sa.Text(),
                type_=sa.VARCHAR(),
                existing_nullable=True)
    # ### end Alembic commands ###