"""add workflow launch history

Revision ID: f3d2ac0d7966
Revises: a495b3d89373
Create Date: 2026-08-24 08:29:17.973571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d2ac0d7966'
down_revision = 'a495b3d89373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_workflow_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['admin_workflow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_workflow_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_workflow_run_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('admin_task_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_run_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'admin_workflow_run', ['workflow_run_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_task_run', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('workflow_run_id')

    with op.batch_alter_table('admin_workflow_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_workflow_run_uuid'))

    op.drop_table('admin_workflow_run')
    # ### end Alembic commands ###
